function [methodinfo,structs,enuminfo,ThunkLibName]=LinInterpolProto
%LININTERPOLPROTO Create structures to define interfaces found in 'LinInterpol'.

%This function was generated by loadlibrary.m parser version  on Thu Feb  9 09:07:30 2017
%perl options:'LinInterpol.i -outfile=LinInterpolProto.m -thunkfile=LinInterpol_thunk_pcwin64.c -header=LinInterpol.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'LinInterpol_thunk_pcwin64');
% int LinInterpol ( double * yq , double * xx , double * yy , double * xq , int nx , int nq ); 
fcns.thunkname{fcnNum}='int32voidPtrvoidPtrvoidPtrvoidPtrint32int32Thunk';fcns.name{fcnNum}='LinInterpol'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'doublePtr', 'doublePtr', 'doublePtr', 'doublePtr', 'int32', 'int32'};fcnNum=fcnNum+1;
% int LinInterpolAdd4Async ( double * yq , double * xq , int nq , double * xx0 , double * yy0 , int nx0 , double * xx1 , double * yy1 , int nx1 , double * xx2 , double * yy2 , int nx2 , double * xx3 , double * yy3 , int nx3 ); 
fcns.thunkname{fcnNum}='int32voidPtrvoidPtrint32voidPtrvoidPtrint32voidPtrvoidPtrint32voidPtrvoidPtrint32voidPtrvoidPtrint32Thunk';fcns.name{fcnNum}='LinInterpolAdd4Async'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'doublePtr', 'doublePtr', 'int32', 'doublePtr', 'doublePtr', 'int32', 'doublePtr', 'doublePtr', 'int32', 'doublePtr', 'doublePtr', 'int32', 'doublePtr', 'doublePtr', 'int32'};fcnNum=fcnNum+1;
methodinfo=fcns;