clear;
cri = readmatrix('CRI_Spectra.csv'); %95x16
cri = cat(2,cri,ones(size(cri(:,1))));
%%
names = cell(1,16);
for i = 1:16 
    names{i} = sprintf('TCS%02i',i);
end

descriptors = {'Light greyish red',...
'Dark greyish yellow',...
'Strong yellow green',...
'Moderate yellowish green',...
'Light bluish green',...
'Light blue',...
'Light violet',...
'Light reddish purple',...
'Strong red',...
'Strong yellow',...
'Strong green',...
'Strong blue',...
'Light yellowish pink',...
'Moderate olive green',...
'Japanese skin',...
'Perfect white'};

munsells = {...
'7.5  R 6/4',...
'5  Y6/4',...
'5 GY 6/8',...
'2.5 G 6/6',...
'10 BG 6/4',...
'5 PB 6/8',...
'2.5 P 6/8',...
'10 P 6/8',...
'4.5 R 4/13',...
'5 Y 8/10',...
'4.5 G 5/8',...
'3 PB 3/11',...
'5 YR 8/4',...
'5 GY 4/4',...
'unknown',...
'unknown'};
    

for i = 1:16
    si.lam = cri(:,1);
    si.val = cri(:,i+1);
    si.name = names{i};
    si.description = descriptors{i};
    si.munsell = munsells{i};
    CRISpectra(i) = si;
end
%%
figure(1);
clf;
hold on;
for i=1:16
    plot(CRISpectra(i).lam, CRISpectra(i).val);
end
legend(descriptors,'Location','NorthEastOutside');
title('CRI 13.3-1995 reflectivity spectra');
xlabel('\lambda (nm)');
ylabel('reflectivity');
axis([350,850,-0.05,1.05]);
grid on;
%%
save('CRISpectra.mat','CRISpectra');